### ISSUE TITLE
Owner is a PEDO BE WARNED

### ISSUE THREAD

**Issue by StarnightLibraryPedo** [StarnightLibrary/starnight#7]
Owner claims to be female to touch LITTLE BOYS BE WARNED

**Comment by OoLunar** [comment]
I can confirm that this is false. Please take your tomfoolery somewhere else.

**Comment by StarnightLibraryPedo** [comment]
> I can confirm that this is false. Please take your tomfoolery somewhere else.

bullshit pedo

**Comment by JulianusIV** [comment]
> > I can confirm that this is false. Please take your tomfoolery somewhere else.
> 
> bullshit pedo

go touch some grass

**Comment by StarnightLibraryPedo** [comment]
> > > I can confirm that this is false. Please take your tomfoolery somewhere else.
> > 
> > 
> > bullshit pedo
> 
> go touch some grass

say you pedo kid toucher

**Comment by StarnightLibraryPedo** [comment]
https://github.com/StarnightLibrary/starnight/assets/134529239/850544b2-9201-45c3-b69c-a4c3b1fc2bf8
